config/routes.rb
Rails.application.routes.draw do
  
  root "villas#index"

  get 'signup'  => 'users#new'
  get 'signin'  => 'sessions#new'
  get 'make_contract'  => 'contracts#make_contract'
  
  resources :users, :featureds, :features, :areas, :collections, :owners, :rates, :contracts 
  
  resource :session
  
  resources :villas do
    resources :types
    resources :wishlist
  end

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :villas
end

app/models/base_contract.rb
class BaseContract < ActiveRecord::Base
  
  LANGUAGES = ["English", "Italian", "French"]
  
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  
  validates :name, presence: true, uniqueness: true
  
  validates :description, length: {minimum: 30}
  
  has_many :types, dependent: :destroy
  
  has_many :selected_villas, through: :types, source: :villa
  
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  
  YEARS = [2015, 2016, 2017, 2018, 2019]
  
  CURRENCIES = ['EUR', 'GBP', 'USD']
  
  CONTRACT_TYPES = ['Exclusive', 'Time Limited Exclusive', 'Priority', 'Non Exclusive']
  
  DAYS = ['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
  
  PAYMENT_TERMS = ['End of Month of Stay', 'Start of Month of Stay', '30 days before stay', '60 days before stay']
  
  validates :year, presence: true
  validates :villa_id, presence: true
  
  validates :currency, inclusion: { 
            in: CURRENCIES, 
            message: "must be euro, sterling or dollar."
          }
  
  validates :contract, inclusion: { 
            in: CONTRACT_TYPES, 
            message: "must be one of our contract types." 
          }
  
  validates :week_start, inclusion: { 
            in: DAYS, 
            message: "must be a day of the week."
          }
          
  belongs_to :villa
  has_many :rates, dependent: :destroy
  
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_many :featureds, dependent: :destroy
  has_many :villas_with_feature, through: :featureds, source: :villa
end

app/models/featured.rb
class Featured < ActiveRecord::Base
  belongs_to :villa
  belongs_to :feature
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  
  has_many :villas
  
  has_many :contracts, through: :villas
  
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  
  validates :net, numericality: true
  
  validates :name, presence: true
  
  belongs_to :contract
  validates :contract, presence: true
end

app/models/type.rb
class Type < ActiveRecord::Base
  belongs_to :villa
  belongs_to :collection
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
  
  validates :name, presence: true
  validates :email, presence: true,
                    format: /\A\S+@\S+\z/,
                    uniqueness:  { case_sensitive: false }
end

app/models/villa.rb
class Villa < ActiveRecord::Base
  
  before_validation :generate_slug

  def self.search(sleeps)
    if sleeps
      min = sleeps.to_i
      max = sleeps.to_i + 4
      where("sleeps >= ? AND sleeps < ?", min, max) 
    else
      all
    end
  end
  
  def generate_slug
      self.slug ||= name.parameterize if name
  end
  
  def to_param
    slug
  end

  #scope :sleeps, -> (sleeps = 1) { where("sleeps >= ? AND sleeps < ?", sleeps, sleeps + 4) }
  
  #scope :area, -> { where("villa.area = 2")}
  
  has_attached_file :image
  
  has_many :types, dependent: :destroy
  
  has_many :collections, through: :types
  
  has_many :featureds, dependent: :destroy
  
  has_many :features, through: :featureds
  
  has_many :contracts, dependent: :destroy
  
  belongs_to :area
  
  belongs_to :owner
  
  validates :name, :strapline, presence: true, uniqueness: true
  
  validates :slug, uniqueness: true
  
  validates :reference, numericality: {greater_than_or_equal_to: 0}
  
  validates :description, length: {minimum: 30}
  
  validates_attachment :image,
    :content_type => { :content_type => ['image/jpeg', 'image/png'] },
    :size => { :less_than => 1.megabyte }
  

  
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  
end

app/controllers/villas_controller.rb
class VillasController < ApplicationController
  
  def index
    @villas = Villa.search(params[:sleeps])
    @areas = Area.all
        
    @hash = Gmaps4rails.build_markers(@villas) do |villa, marker|
      marker.lat villa.latitude
      marker.lng villa.longitude
      marker.infowindow render_to_string(:partial => "/villas/infowindow", :locals => { :villa => villa})
          marker.title "#{villa.name}"
          marker.json({ :sleeps => villa.sleeps})
          marker.picture({:picture => "http://mapicons.nicolasmollet.com/wp-content/uploads/mapicons/shape-default/color-3875d7/shapecolor-color/shadow-1/border-dark/symbolstyle-contrast/symbolshadowstyle-dark/gradient-iphone/information.png",
                          :width => 32,
                          :height => 32})
    end
  end
  
  def show
    @villa = Villa.find_by(slug: params[:id])
    @collections = @villa.collections
    @features = @villa.features
  end
  
  def edit
    @villa = Villa.find_by(slug: params[:id])
  end
  
  def update
    @villa = Villa.find_by(slug: params[:id])
    if @villa.update(villa_params)
      redirect_to @villa
    else
      render :edit
    end
  end
  
  def new
    @villa = Villa.new
    @owners = Owner.all
  end
  def create
    @villa = Villa.new(villa_params)
    if @villa.save
      redirect_to @villa
    else
      render :new
    end
  end
  
  def destroy
    @villa = Villa.find_by(slug: params[:id])
    @villa.destroy
    redirect_to @villa
  end
  
  def remember
    cookies[:wishlist] = @villa.id
    redirect_to @villa
  end
end

private

def villa_params
  params.require(:villa).permit(:owner_id, :name, :address, :reference, :strapline, :description, :sleeps, :area_id, :latitude, :longitude, :original_name, :accommodation, :around_the_villa, :number_of_bedrooms, :bed_and_bathrooms, :rental_day,  :image_file_name, collection_ids: [], feature_ids: [])
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
  #def generate_contract
  #  if File.exists?('files/english_base.md')
  #    file = File.open('files/english_base.md')
  #    base_contract = file.read
  #  end
  #end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper

end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/villas_helper.rb
module VillasHelper
  
  def villa_page_title
    if @villa.area.name.nil?
      @villa.name
    else
      @villa.area.name+" - "+@villa.name
    end
  end
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/views/villas/_form.html.erb
<%= form_for(@villa) do |f| %>

<%= render "shared/errors", object: @villa %>
<fieldset>
	<ol>
	<li>
		<p>Select an owner</p>
		<%= collection_select(:villa, :owner_id, Owner.order(:surname), :id, :surname, prompt: true ) %>
	</li>
	<li class = "required">
		<%= f.label :name %>
		<%= f.text_field :name, autofocus: true %>
	</li>	<li class = "required">
		<%= f.label :original_name %>
		<%= f.text_field :original_name %>
	</li>
	<li class = "required">
		<%= f.label :reference %>
		<%= f.number_field :reference %>
	</li>
	<li class = "required">
		<%= f.label :rental_day %>
		<%= f.text_field :rental_day %>
	</li>
	<li class = "required">
		<%= f.label :sleeps %>
		<%= f.number_field :sleeps %>
	</li>
	<li class = "required">
		<%= f.label :number_of_bedrooms %>
		<%= f.number_field :number_of_bedrooms %>
	</li>
	<li class = "required">
		<%= f.label :bed_and_bathrooms %>
		<%= f.text_area( :bed_and_bathrooms, cols: 30, rows:3 ) %>
	</li>
	<li class = "required">
		<%= f.label :address %>
		<%= f.text_field :address %>
	</li>
	<li class = "required">
		<%= f.label :latitude %>
		<%= f.text_field :latitude %>
	</li>
	<li class = "required">
		<%= f.label :longitude %>
		<%= f.text_field :longitude %>
	</li>
	<li class = "required">
		<%= f.label :strapline %>
		<%= f.text_area( :strapline, cols: 30, rows:5 ) %>
	</li>
	<li class = "required">
		<%= f.label :description %>
		<%= f.text_area( :description, cols: 30, rows:5 ) %>
	</li>
	<li class = "required">
		<%= f.label :accommodation %>
		<%= f.text_area( :accommodation, cols: 30, rows:5 ) %>
	</li>
	<li class = "required">
		<%= f.label :around_the_villa %>
		<%= f.text_area( :around_the_villa, cols: 30, rows:5 ) %>
	</li>
	<li>
	  <%= f.label :image %>
	  <%= f.file_field :image %>
	</li>
	<p>Features</p><hr />
	<li>
		<%= f.collection_check_boxes(:feature_ids, Feature.all, :id, :name) %>
	</li>
	<p>Collections</p><hr />
	<li>
		<%= f.collection_check_boxes(:collection_ids, Collection.all, :id, :name) %>
	</li>
	</ol>
	<p><%= f.submit %></p>
	</fieldset>
<% end %>

app/views/villas/_infowindow.html.erb
<h4><%= link_to villa.name, villa %></h4>
<h4>Sleeps: <%= villa.sleeps %></h4>

app/views/villas/edit.html.erb
<h1>Updating: <%= @villa.name %></h1>

<%= render 'form' %>

app/views/villas/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> 

<!-- only if you need custom infoboxes -->

<h1><%= pluralize(@villas.size, 'Villa') %></h1>
<ul id="events">	
	<% @villas.each do |villa| %>
	<li>
		<article class="event">
			<header>
		<h2><%= link_to villa.name, villa %> - Ref.:<%= villa.reference %></h2>
		</header>
		<p><%= image_tag(villa.image_file) %></p>
		<h3>Sleeps <%= villa.sleeps %></h3>
		<p><%= truncate(villa.description, length: 120, separator: " "  )  %>
			<%= link_to 'read more...', villa %></p>
		</article>
	</li>
	<% end %>
	</ul>
	<div style='width: 800px;'>
		<div id="map" style='width: 800px; height: 400px;'>
	
	
<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	  markers = handler.addMarkers( <%=raw @hash.to_json %> );
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
	});
	</script>
	</div> 

app/views/villas/new.html.erb
<h1>Add a Villa</h1>

<%= render 'form' %>

app/views/villas/show.html.erb
<article id="event" class="event">
	<h2><%= @villa.name %> - Ref.:<%= @villa.reference %></h2>
	<p><%= image_tag(@villa.image_file_name) %></p>
	<p>Sleeps <%= @villa.sleeps %></p>
	<p><%= @villa.address %> ( in area name link)</p>
	<h4><%= @villa.strapline %></h4>
	<p><%= @villa.description %></p>
	<p><%= @villa.accommodation %></p>
	<p><%= @villa.around_the_villa %></p>
	
	<% content_for(:title) do %>
		| <%= @villa.name %> | <%= @villa.address %> | 
	<% end %>

	<% content_for(:side) do %>
	<p>Sleeps: <%= @villa.sleeps %>
	<p><%= @villa.bed_and_bathrooms %></p>
		<p>Features:</p>
		<ul>
			<% @features.each do |f| %>
			<li><%= f.name %></li>
			<% end %>
		</ul>
		<p>In <%= pluralize @collections.size, 'collection' %></p>
		<ol>
			<% @collections.each do |c| %>
			<li><%= link_to c.name, c %></li>
			<% end %>
		</ol>
	<% end %>
</article>

<%= link_to "Back to List of Villas", villas_url  %> | <%= link_to "Edit", edit_villa_path(@villa) %> | <%= link_to "Delete", villa_path(@villa), method: :delete, data: { confirm: 'Are you sure?'}  %> | <%= link_to "Contracts", contracts_path(villa_id: @villa) %> | <%= link_to 'Add a Contract', new_contract_path(@villa) %>