config/routes.rb
Rails.application.routes.draw do
  
  root "villas#index"

  get 'signup'  => 'users#new'
  get 'signin'  => 'sessions#new'
  get 'make_contract'  => 'contracts#make_contract'
  
  resources :users, :featureds, :features, :areas, :collections, :owners, :rates, :contracts 
  
  resource :session
  
  resources :villas do
    resources :types
    resources :wishlist
  end

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :villas
end

app/models/base_contract.rb
class BaseContract < ActiveRecord::Base
  
  LANGUAGES = ["English", "Italian", "French"]
  
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  
  validates :name, presence: true, uniqueness: true
  
  validates :description, length: {minimum: 30}
  
  has_many :types, dependent: :destroy
  
  has_many :selected_villas, through: :types, source: :villa
  
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  
  YEARS = [2015, 2016, 2017, 2018, 2019]
  
  CURRENCIES = ['EUR', 'GBP', 'USD']
  
  CONTRACT_TYPES = ['Exclusive', 'Time Limited Exclusive', 'Priority', 'Non Exclusive']
  
  DAYS = ['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
  
  PAYMENT_TERMS = ['End of Month of Stay', 'Start of Month of Stay', '30 days before stay', '60 days before stay']
  
  validates :year, presence: true
  validates :villa_id, presence: true
  
  validates :currency, inclusion: { 
            in: CURRENCIES, 
            message: "must be euro, sterling or dollar."
          }
  
  validates :contract, inclusion: { 
            in: CONTRACT_TYPES, 
            message: "must be one of our contract types." 
          }
  
  validates :week_start, inclusion: { 
            in: DAYS, 
            message: "must be a day of the week."
          }
          
  belongs_to :villa
  has_many :rates, dependent: :destroy
  
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_many :featureds, dependent: :destroy
  has_many :villas_with_feature, through: :featureds, source: :villa
end

app/models/featured.rb
class Featured < ActiveRecord::Base
  belongs_to :villa
  belongs_to :feature
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  
  has_many :villas
  
  has_many :contracts, through: :villas
  
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  
  validates :net, numericality: true
  
  validates :name, presence: true
  
  belongs_to :contract
  validates :contract, presence: true
end

app/models/type.rb
class Type < ActiveRecord::Base
  belongs_to :villa
  belongs_to :collection
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
  
  validates :name, presence: true
  validates :email, presence: true,
                    format: /\A\S+@\S+\z/,
                    uniqueness:  { case_sensitive: false }
end

app/models/villa.rb
class Villa < ActiveRecord::Base
  
  before_validation :generate_slug

  def self.search(sleeps)
    if sleeps
      min = sleeps.to_i
      max = sleeps.to_i + 4
      where("sleeps >= ? AND sleeps < ?", min, max) 
    else
      all
    end
  end
  
  def generate_slug
      self.slug ||= name.parameterize if name
  end
  
  def to_param
    slug
  end

  #scope :sleeps, -> (sleeps = 1) { where("sleeps >= ? AND sleeps < ?", sleeps, sleeps + 4) }
  
  #scope :area, -> { where("villa.area = 2")}
  
  has_attached_file :image
  
  has_many :types, dependent: :destroy
  
  has_many :collections, through: :types
  
  has_many :featureds, dependent: :destroy
  
  has_many :features, through: :featureds
  
  has_many :contracts, dependent: :destroy
  
  belongs_to :area
  
  belongs_to :owner
  
  validates :name, :strapline, presence: true, uniqueness: true
  
  validates :slug, uniqueness: true
  
  validates :reference, numericality: {greater_than_or_equal_to: 0}
  
  validates :description, length: {minimum: 30}
  
  validates_attachment :image,
    :content_type => { :content_type => ['image/jpeg', 'image/png'] },
    :size => { :less_than => 1.megabyte }
  

  
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end
  
  def show
    @owner = Owner.find(params[:id])
    @villas = @owner.villas
  end
  
  def edit
    @owner = Owner.find(params[:id])
  end
  
  def update
    @owner = Owner.find(params[:id])
    if @owner.update(owner_params)
      redirect_to @owner
    else
      render :edit
    end
  end
  
  def new
    @owner = Owner.new
  end
  
  def create
      @owner = Owner.new(owner_params)
      if @owner.save
        redirect_to @owner
      else
        render :new
      end
  end
  
  private
  
  def owner_params
    params.require(:owner).permit(:title, :name, :surname, :company, :address, :postcode, :country, :language, :phone, :mobile, :email, :notes, :private_notes)
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
  #def generate_contract
  #  if File.exists?('files/english_base.md')
  #    file = File.open('files/english_base.md')
  #    base_contract = file.read
  #  end
  #end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper

end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/villas_helper.rb
module VillasHelper
  
  def villa_page_title
    if @villa.area.name.nil?
      @villa.name
    else
      @villa.area.name+" - "+@villa.name
    end
  end
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>

<%= render "shared/errors", object: @owner %>
<fieldset>
	<ol>
<li class = "required">
	<%= f.label :title %>
	<%= f.text_field :title %>
</li>
<li class = "required">
	<%= f.label :name %>
	<%= f.text_field :name, autofocus: true %>
</li>
<li class = "required">
	<%= f.label :surname %>
	<%= f.text_field :surname %>
</li>
<li class = "required">
	<%= f.label :company %>
	<%= f.text_field :company %>
</li>
<li class = "required">
	<%= f.label :language %>
	<%= f.text_field :language %>
</li>
<li class = "required">
	<%= f.label :address %>
	<%= f.text_field :address %>
</li>
<li class = "required">
	<%= f.label :postcode %>
	<%= f.text_field :postcode %>
</li>
<li class = "required">
	<%= f.label :country %>
	<%= f.text_field :country %>
</li>
<li class = "required">
	<%= f.label :phone %>
	<%= f.text_field :phone %>
</li>
<li class = "required">
	<%= f.label :mobile %>
	<%= f.text_field :mobile %>
</li>
<li class = "required">
	<%= f.label :email %>
	<%= f.text_field :email %>
</li>
<li class = "required">
	<%= f.label :notes %>
	<%= f.text_area( :notes, cols: 30, rows:5 ) %>
</li>
<li class = "required">
	<%= f.label :private_notes %>
	<%= f.text_area( :private_notes, cols: 30, rows:5 ) %>
</li>

<p><%= f.submit %></p>
<% end %>

app/views/owners/edit.html.erb
<h1>Edit details for <%= full_name(@owner) %></h1>

<%= render 'form' %>

app/views/owners/index.html.erb
<header>
	
	<h1><%= pluralize(@owners.size, 'Owner') %></h1>
</header>
<article>
	<ul>
		<% @owners.each do |owner| %>
		<li>
		 <p> <%= link_to full_name(owner), owner %> - preferred language: <%= owner.language %></p>
		 
		</li>	
		<% end %>
	</ul>
</article>

app/views/owners/new.html.erb
<h1>Add a new owner</h1>

<%= render 'form' %>

app/views/owners/show.html.erb
<header>
	<h1><%= mail_to @owner.email, full_name(@owner) %></h1>
</header>
<article>
	<h4>Tel.: <%= number_to_phone(@owner.phone) %> - Mob.: <%= number_to_phone(@owner.mobile) %></h4>
	
	<p><%= link_to 'Edit this Owner', edit_owner_path(@owner) %></p>
	<p><%= link_to 'Add a New Villa for this Owner', new_villa_path(owner_id: @owner.id) %></p>
	<h4>Notes</h4>
	<p><%= @owner.notes %><p>
	<h4>Private Notes</h4>
	<p><%= @owner.private_notes %><p>
	<ul>
		<% @villas.each do |villa| %>	
		<li>
			<h2><%= link_to villa.name, villa %> - Ref.:<%= villa.reference %></h2>
			<p><%= image_tag(villa.image_file) %></p>
			<p>Sleeps <%= villa.sleeps %></p>
			<p><%= link_to 'View villa', villa %> | <%= link_to 'Edit Villa', edit_villa_path(villa) %>
		</li><hr />
		<% end %>
	</ul>
		
	<% content_for(:side) do %>
		<p><strong>Address</strong></p>
		<p><%= @owner.address %><br />
		<%= @owner.postcode %><br />
		<%= @owner.country %></p>
	<% end %>
</article>