config/routes.rb
Rails.application.routes.draw do
  
  root "villas#index"

  get 'signup'  => 'users#new'
  get 'signin'  => 'sessions#new'
  get 'make_contract'  => 'contracts#make_contract'
  
  resources :users, :featureds, :features, :areas, :collections, :owners, :rates, :contracts 
  
  resource :session
  
  resources :villas do
    resources :types
    resources :wishlist
  end

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :villas
end

app/models/base_contract.rb
class BaseContract < ActiveRecord::Base
  
  LANGUAGES = ["English", "Italian", "French"]
  
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  
  validates :name, presence: true, uniqueness: true
  
  validates :description, length: {minimum: 30}
  
  has_many :types, dependent: :destroy
  
  has_many :selected_villas, through: :types, source: :villa
  
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  
  YEARS = [2015, 2016, 2017, 2018, 2019]
  
  CURRENCIES = ['EUR', 'GBP', 'USD']
  
  CONTRACT_TYPES = ['Exclusive', 'Time Limited Exclusive', 'Priority', 'Non Exclusive']
  
  DAYS = ['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
  
  PAYMENT_TERMS = ['End of Month of Stay', 'Start of Month of Stay', '30 days before stay', '60 days before stay']
  
  validates :year, presence: true
  validates :villa_id, presence: true
  
  validates :currency, inclusion: { 
            in: CURRENCIES, 
            message: "must be euro, sterling or dollar."
          }
  
  validates :contract, inclusion: { 
            in: CONTRACT_TYPES, 
            message: "must be one of our contract types." 
          }
  
  validates :week_start, inclusion: { 
            in: DAYS, 
            message: "must be a day of the week."
          }
          
  belongs_to :villa
  has_many :rates, dependent: :destroy
  
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_many :featureds, dependent: :destroy
  has_many :villas_with_feature, through: :featureds, source: :villa
end

app/models/featured.rb
class Featured < ActiveRecord::Base
  belongs_to :villa
  belongs_to :feature
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  
  has_many :villas
  
  has_many :contracts, through: :villas
  
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  
  validates :net, numericality: true
  
  validates :name, presence: true
  
  belongs_to :contract
  validates :contract, presence: true
end

app/models/type.rb
class Type < ActiveRecord::Base
  belongs_to :villa
  belongs_to :collection
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
  
  validates :name, presence: true
  validates :email, presence: true,
                    format: /\A\S+@\S+\z/,
                    uniqueness:  { case_sensitive: false }
end

app/models/villa.rb
class Villa < ActiveRecord::Base
  
  before_validation :generate_slug

  def self.search(sleeps)
    if sleeps
      min = sleeps.to_i
      max = sleeps.to_i + 4
      where("sleeps >= ? AND sleeps < ?", min, max) 
    else
      all
    end
  end
  
  def generate_slug
      self.slug ||= name.parameterize if name
  end
  
  def to_param
    slug
  end

  #scope :sleeps, -> (sleeps = 1) { where("sleeps >= ? AND sleeps < ?", sleeps, sleeps + 4) }
  
  #scope :area, -> { where("villa.area = 2")}
  
  has_attached_file :image
  
  has_many :types, dependent: :destroy
  
  has_many :collections, through: :types
  
  has_many :featureds, dependent: :destroy
  
  has_many :features, through: :featureds
  
  has_many :contracts, dependent: :destroy
  
  belongs_to :area
  
  belongs_to :owner
  
  validates :name, :strapline, presence: true, uniqueness: true
  
  validates :slug, uniqueness: true
  
  validates :reference, numericality: {greater_than_or_equal_to: 0}
  
  validates :description, length: {minimum: 30}
  
  validates_attachment :image,
    :content_type => { :content_type => ['image/jpeg', 'image/png'] },
    :size => { :less_than => 1.megabyte }
  

  
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  #before_action :set_villa
  
  def index
    @contracts = Contract.where(:villa_id  => params[:villa_id]).order("year DESC")
    @villa = Villa.find(params[:villa_id])
  end
  
  def show
    @contract = Contract.find(params[:id])
    @villa = @contract.villa
    @owner = @villa.owner
    @rates = @contract.rates
  end
  
  def new
    @villa = Villa.find(params[:villa_id])
    session[:villa_id] = params[:villa_id]
    @owner = @villa.owner
    @contract = @villa.contracts.new
  end
  
  def create
    @villa = Villa.find(session[:villa_id])
    @contract = Contract.new(contract_params)
    if @contract.save
      redirect_to contracts_path(@contract.villa_id),
      notice: "New contract generated"
    else
      render :new
    end
  end
  
  def edit
     @contract = Contract.find(params[:id])
  end
   
   def update
     
   end
   
   def destroy
     @contract = Contract.find(params[:id])
     @contract.destroy
     redirect_to contracts_path(@villa)
  end
  
  def make_contract
    @contract = Contract.find(params[:contract_id])
    @villa = @contract.villa
    @owner = @villa.owner
    @rates = @contract.rates
    @villas = @owner.villas
  end
   
   private
   
   def contract_params
     params.require(:contract).permit(:year, :start_date, :end_date, :commission, :currency, :contract, :payment_terms, :week_start, :villa_id)
   end
   
   def set_villa

   end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
  #def generate_contract
  #  if File.exists?('files/english_base.md')
  #    file = File.open('files/english_base.md')
  #    base_contract = file.read
  #  end
  #end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper

end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/villas_helper.rb
module VillasHelper
  
  def villa_page_title
    if @villa.area.name.nil?
      @villa.name
    else
      @villa.area.name+" - "+@villa.name
    end
  end
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/views/contracts/_english_contract.html.erb
<h1>Contract for Owner</h1>

<p>AGREEMENT BETWEEN</p>
<article>
<p>Invitation to Tuscany Ltd.</p><p>
Winston House</p><p>
London N3 1HF</p><p>
Tel. +44 (0)208 444 9500</p><p>
Fax +44 (0)208 371 5949</p><p>
registered at Companies House with the n° 5399312</p><p>
hereinafter also referred to as "the Agent" on the one part and</p><p>
</p>
</article>
<p>

<p>Name: <%= full_name(@owner) %></p>
<p>Company: <%= @owner.company %>
<p>Address: <%= @owner.address %> - </p>
<p><%= @owner.postcode %> - <%= @owner.country %></p>
<p>Tel.:<%= @owner.phone %></p>	
<p>Mobile:	<%= @owner.mobile %></p>
<p>Email: <%= @owner.email %>	</p>

<p> Hereinafter referred to as "the Principal" on the other part.</p>

<p>GIVEN<br />
that the Agent promotes the rental property for use as holiday accommodation on behalf of the Principal, the Principal hereby appoints the Agent as its selling agent in the United Kingdom, Europe, Scandinavia, the United States of America, Canada, Australia and New Zealand in respect of the rental of the Principal’s holiday accommodation and the Agent agrees to act as such. The Agent undertakes to deal accurately with requests for bookings from the Principals’ customers, and to relay all monies which it receives from the Principals’ customers which were due to the Principal under the terms of this Agreement including payment for the holiday, any cancellation charges and collection of funds for the cautionary deposit. The Agent has no further duties toward the Principal in this agreement, except that he may act on behalf of the Principal to remedy equipment or property breakdowns in the case that the Principal (or his representative) is unavailable.<br />
IT IS AGREED AND STIPULATED AS FOLLOWS:</p>

<p>1)	The Principal grants permission for the Agent to promote, negotiate and conclude in his name and on his account contracts to let and use as holiday accommodation of the following property: </p>

	<p>Property name: <%= @villa.name %><br />
	<p>Maximum people allowed: <%= @villa.sleeps %><br />
	<p>Situated in: <%= @villa.address %></p>
	<p>for periods from 3 days to 3 months, but generally for 1 – 2 weeks and in accordance with the conditions and prices in the Paragraphs here below.</p>
	<p>a)	The property is completely restored and furnished and does not/does require further works. (If there are works to be done they should be described and attached to the bottom of this agreement.)</p>

<p>b)	Heating is included / not included (strike out the option that does not apply)
Notes on heating (fire wood, etc.) ___________________________________
</p>
<p>c)	The weekly rental prices for <%= @contract.year %> are established as below, less any small bank charges.</p>

<% @rates.each do |rate| %>
	<p><strong><%= rate.name %></strong>
				Starts: <%= make_date(rate.start_date) %> | Ends <%= make_date(rate.end_date) %> | <strong>Net Rate: <%= number_to_currency(rate.net, locale: :it) %></strong> -- giving a EUR selling price of <%= number_to_currency(rate.net/((100-@contract.commission))*100, locale: :it) %>
<% end %>
<p>2)	Any further alteration in price after signing of the Agreement shall be notified by the Principal to the Agent by no later than 31st December <%= @contract.year.to_i - 1 %>. Any price alteration to the Principal customer's holiday can not be made once the customer has made full payment.</p>

app/views/contracts/_form.html.erb
<%= form_for @contract do |f| %>

<%= render "shared/errors", object: @contract %>

<fieldset>
	<ol>
	<li class = "required">
		<%= f.label :year %>
		<%= f.select :year, Contract::YEARS, prompt: 'Pick One' %>
	</li>
	<li class = "required">
		<%= f.label :start_date %>
		<%= f.date_field :start_date %>
		Earliest date bookings can start.
	</li>
	<li class = "required">
		<%= f.label :end_date %>
		<%= f.date_field :end_date %>
		Last date bookings can be taken.
	</li>
	<li class = "required">
		<%= f.label :commission %>
		<%= f.number_field :commission %>
		Default is 30%
	</li>
	<li class = "required">
		<%= f.label :currency %>
		<%= f.select :currency, Contract::CURRENCIES %>
	</li>
	<li class = "required">
		<%= f.label :contract %>
		<%= f.select :contract, Contract::CONTRACT_TYPES %>
	</li>
	<li class = "required">
		<%= f.label :payment_terms %>
		<%= f.select :payment_terms, Contract::PAYMENT_TERMS %>
	</li>
	<li class = "required">
		<%= f.label :week_start%>
		<%= f.select :week_start, Contract::DAYS %>
	</li>
		<%= f.hidden_field :villa_id, :value  => session[:villa_id] %>

	<p><%= f.submit %></p>
	</ol>
</fieldset>
<% end %>

app/views/contracts/_french_contract.html.erb
<h1>Contrat Francais</h1>

app/views/contracts/_italian_contract.html.erb
<h1>Contratto in Italiano</h1>

app/views/contracts/edit.html.erb
<h1>Edit contract</h1>

<%= render 'form' %>

app/views/contracts/index.html.erb
<header>
	<h1>Contracts for <%= link_to @villa.name, @villa %></h1>
</header>

<article>
	<p><%= link_to 'Add a Contract', new_contract_path(villa_id: @villa) %>
	<ul>
		<% @contracts.each do |contract| %>
		<li>
			<h4>Contract for 
			<%= link_to contract.year, contract_path(contract)%>.  </h4><p>Created on <%= time_tag contract.created_at %> | <%= link_to 'Delete this Contract', contract_path(contract), method: :delete, data: { confirm: 'Are you sure?'}  %></p>
		</li>
		<% end %>
	</ul>
</article>

app/views/contracts/make_contract.html.erb
<% case @owner.language %>
<% when "english" %>
<%= render 'english_contract' %>
<% when "italian" %>
<%= render 'italian_contract' %>
<% when 'french' %>
<%= render 'french_contract' %>
<% else %>
<%= puts "No language set" %>
<% end %>

app/views/contracts/new.html.erb
<h1>Add a Year Contract</h1>


<%= render 'form' %>

app/views/contracts/show.html.erb
<header>
	<h1><%= @contract.year %> contract for <%= @villa.name %></h1>
	<h4>Owner <%= full_name(@owner) %>. Preferred language: <%= @owner.language %></h4>
</header>
<article>
	<p>Year: <%= @contract.year %></p>
	<p>Currency: <%= @contract.currency %></p>
	<p>Commission: <%= number_to_percentage ( @contract.commission) %></p>
	<p>Contract start date: <%= @contract.start_date %></p>
	<p>Contract end date: <%= @contract.end_date %></p>
	<p>Payment terms: <%= @contract.payment_terms %></p>
	<p>Contract: <%= @contract.contract %></p>
</article>
<hr />
<article class='event'>
	<p><strong>Rates</strong> | <%= link_to 'Add a Rate', new_rate_path(contract_id: @contract, villa_id: @villa)  %>
	<ul>
		<% @rates.each do |rate| %>
		<li>
			<p><strong><%= rate.name %></strong>
			Starts: <%= make_date(rate.start_date) %> | Ends <%= make_date(rate.end_date) %> | <strong>Net Rate: <%= number_to_currency(rate.net, locale: :it) %></strong> -- giving a selling price of <%= number_to_currency(rate.net/((100-@contract.commission))*100, locale: :it) %>
			| <%= link_to "Delete this rate", rate_path(rate), method: :delete, data: { confirm: 'Are you sure?'}  %></p>
		<% end %>
	</ul>
	<hr />
	<h4><%= link_to 'Generate Contract', make_contract_path(:contract_id  => @contract.id) %></h4>
</article>