config/routes.rb
Rails.application.routes.draw do
  
  root "villas#index"

  get 'signup'  => 'users#new'
  get 'signin'  => 'sessions#new'
  get 'make_contract'  => 'contracts#make_contract'
  
  resources :users, :featureds, :features, :areas, :collections, :owners, :rates, :contracts 
  
  resource :session
  
  resources :villas do
    resources :types
    resources :wishlist
  end

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :villas
end

app/models/base_contract.rb
class BaseContract < ActiveRecord::Base
  
  LANGUAGES = ["English", "Italian", "French"]
  
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  
  validates :name, presence: true, uniqueness: true
  
  validates :description, length: {minimum: 30}
  
  has_many :types, dependent: :destroy
  
  has_many :selected_villas, through: :types, source: :villa
  
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  
  YEARS = [2015, 2016, 2017, 2018, 2019]
  
  CURRENCIES = ['EUR', 'GBP', 'USD']
  
  CONTRACT_TYPES = ['Exclusive', 'Time Limited Exclusive', 'Priority', 'Non Exclusive']
  
  DAYS = ['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
  
  PAYMENT_TERMS = ['End of Month of Stay', 'Start of Month of Stay', '30 days before stay', '60 days before stay']
  
  validates :year, presence: true
  validates :villa_id, presence: true
  
  validates :currency, inclusion: { 
            in: CURRENCIES, 
            message: "must be euro, sterling or dollar."
          }
  
  validates :contract, inclusion: { 
            in: CONTRACT_TYPES, 
            message: "must be one of our contract types." 
          }
  
  validates :week_start, inclusion: { 
            in: DAYS, 
            message: "must be a day of the week."
          }
          
  belongs_to :villa
  has_many :rates, dependent: :destroy
  
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_many :featureds, dependent: :destroy
  has_many :villas_with_feature, through: :featureds, source: :villa
end

app/models/featured.rb
class Featured < ActiveRecord::Base
  belongs_to :villa
  belongs_to :feature
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  
  has_many :villas
  
  has_many :contracts, through: :villas
  
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  
  validates :net, numericality: true
  
  validates :name, presence: true
  
  belongs_to :contract
  validates :contract, presence: true
end

app/models/type.rb
class Type < ActiveRecord::Base
  belongs_to :villa
  belongs_to :collection
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
  
  validates :name, presence: true
  validates :email, presence: true,
                    format: /\A\S+@\S+\z/,
                    uniqueness:  { case_sensitive: false }
end

app/models/villa.rb
class Villa < ActiveRecord::Base
  
  before_validation :generate_slug

  def self.search(sleeps)
    if sleeps
      min = sleeps.to_i
      max = sleeps.to_i + 4
      where("sleeps >= ? AND sleeps < ?", min, max) 
    else
      all
    end
  end
  
  def generate_slug
      self.slug ||= name.parameterize if name
  end
  
  def to_param
    slug
  end

  #scope :sleeps, -> (sleeps = 1) { where("sleeps >= ? AND sleeps < ?", sleeps, sleeps + 4) }
  
  #scope :area, -> { where("villa.area = 2")}
  
  has_attached_file :image
  
  has_many :types, dependent: :destroy
  
  has_many :collections, through: :types
  
  has_many :featureds, dependent: :destroy
  
  has_many :features, through: :featureds
  
  has_many :contracts, dependent: :destroy
  
  belongs_to :area
  
  belongs_to :owner
  
  validates :name, :strapline, presence: true, uniqueness: true
  
  validates :slug, uniqueness: true
  
  validates :reference, numericality: {greater_than_or_equal_to: 0}
  
  validates :description, length: {minimum: 30}
  
  validates_attachment :image,
    :content_type => { :content_type => ['image/jpeg', 'image/png'] },
    :size => { :less_than => 1.megabyte }
  

  
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper

end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/villas_helper.rb
module VillasHelper
  
  def villa_page_title
    if @villa.area.name.nil?
      @villa.name
    else
      @villa.area.name+" - "+@villa.name
    end
  end
end

app/views/layouts/_footer.html.erb
<footer id="page-footer">
	<hr />
  <p>  
    Copyright &copy; 2013 Invitation to Tuscany Ltd.
  </p>  
  <p>
    ABOUT US | WHY BOOK WITH US? | FOR OWNERS | OWNER LOGIN
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to "Villas", root_path %></h1>
	<nav>
		     <p class = "nav">
		        <%= link_to "Villas", villas_path, class: 'button' %> 
		   
		        <%= link_to "Collections", collections_path, class: 'button' %> 
		     
		        <%= link_to "Areas", areas_path, class: 'button' %> 
		      
		        <%= link_to "Owners", owners_path, class: 'button' %> 
		   
		        <%= link_to "Users", users_path, class: 'button' %> 
		     
		        <%= link_to 'Add an Owner', new_owner_path, class: 'button' %> 
		      
		        <%= link_to 'Add New Villa', new_villa_path, class: 'button' %> 
		      
			<% if current_user %>
			  <%= link_to current_user.name, current_user %>
			<% else %>
			  <%= link_to 'Sign In', signin_path, class: 'button' %>
		      <%= link_to 'Sign Up', signup_path, class: 'button' %>
		    <% end %>
		  </p>
	</nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul> 
	 <li>
		 <%= form_tag villas_path, :method => 'get' do %>
		   <p>
		   	<%= number_field_tag :sleeps, params[:sleeps] %>
			<%= submit_tag :search, :name => nil %>
		   </p>
		 <% end %>
	 </li>
  </nav>
  <%= content_for(:side) %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Invitation to <%= content_for(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div id="wrapper">
 <% if flash[:notice] %>
    <p class="flash notice">
      <%= flash[:notice] %>
    </p>
  <% end %>
  <div id="container">
    <%= render "layouts/sidebar" %>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.titleize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>